[versions]
hubdle = "0.5.0-alpha.10"
node = "3.5.1"

[libraries]
github-nodeGradle-node = { module = "com.github.node-gradle:gradle-node-plugin", version.ref = "node" }

[plugins]
javiersc-hubdle = { id = "com.javiersc.hubdle", version.ref = "hubdle" }
