[versions]
hubdle = "0.7.12"
node = "7.0.2"

[libraries]
github-nodeGradle-node = { module = "com.github.node-gradle:gradle-node-plugin", version.ref = "node" }

[plugins]
javiersc-hubdle = { id = "com.javiersc.hubdle", version.ref = "hubdle" }
