[versions]
hubdle = "0.11.0"
node = "7.1.0"

[libraries]
github-nodeGradle-node = { module = "com.github.node-gradle:gradle-node-plugin", version.ref = "node" }

[plugins]
javiersc-hubdle = { id = "com.javiersc.hubdle", version.ref = "hubdle" }
